[package]
name = "wspick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
directories = "5.0.1"
edit = "0.1.4"
inquire = "0.6.2"
serde = "1.0.164"
serde_derive = "1.0.164"
toml = "0.7.5"
